openapi: 3.0.0
info:
  title: Elefanteca
  version: 0.0.0
paths:
  /api/auth/login/jwt:
    post:
      tags:
        - auth
      description: 'Login com JWT'
      operationId: 7aa2ba8401e13c0f62d8ccaeb57b6b98
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              properties:
                email:
                  type: string
                  example: admin@desativemeemprod.com
                password:
                  type: string
                  example: asdf
              type: object
      responses:
        2XX:
          description: OK
  '/api/authors/{id}':
    get:
      tags:
        - autor
      description: 'Exibição de 1 autor'
      operationId: c14c739d68f46a33acfd0694a12c27dc
      parameters:
        -
          name: id
          in: path
          description: 'Id autor'
          required: true
          schema:
            type: integer
            example: 1
      responses:
        2XX:
          description: OK
      security:
        -
          JWT: []
    put:
      tags:
        - autor
      description: 'Edição de autor'
      operationId: 2a9f154a4061c0d3257520aba98221a5
      parameters:
        -
          name: id
          in: path
          description: 'Id autor'
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              properties:
                name:
                  type: string
                  example: 'Edgar Allan Poe'
              type: object
      responses:
        2XX:
          description: OK
      security:
        -
          JWT: []
    delete:
      tags:
        - autor
      description: 'Deleção de autor'
      operationId: c04021713290d77b82e912ec58f94c36
      parameters:
        -
          name: id
          in: path
          description: 'Id autor'
          required: true
          schema:
            type: integer
            example: 1
      responses:
        2XX:
          description: OK
      security:
        -
          JWT: []
  /api/authors:
    get:
      tags:
        - autor
      description: 'Listagem de autores'
      operationId: 0c71439e213e1b284fc37995d74bca2b
      parameters:
        -
          name: name
          in: query
          description: 'Nome parcial do autor'
          schema:
            type: string
            example: Allan
        -
          name: page
          in: query
          description: Paginação
          schema:
            type: integer
            example: 1
      responses:
        2XX:
          description: OK
      security:
        -
          JWT: []
    post:
      tags:
        - autor
      description: 'Cadastro de autor'
      operationId: 291d8539d3b5490d46fe9f2ebd84c64c
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              properties:
                name:
                  type: string
                  example: 'Edgar Allan Poe'
              type: object
      responses:
        2XX:
          description: OK
      security:
        -
          JWT: []
  /api/users:
    post:
      tags:
        - usuário
      description: 'Cadastro de usuário'
      operationId: 592819a0265360b2014512d6dbfaf0e7
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              properties:
                name:
                  type: string
                  example: Diego
                cpf:
                  type: string
                  example: '37128197060'
                password:
                  type: string
                  example: '19800507'
                email:
                  type: string
                  example: example@foo.com
              type: object
      responses:
        2XX:
          description: OK
      security:
        -
          JWT: []
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
externalDocs:
  description: 'Código fonte do projeto'
  url: 'https://github.com/nenitf/elefanteca_api'
