openapi: 3.0.0
info:
  title: Elefanteca
  version: 0.0.0
paths:
  /api/users:
    post:
      tags:
        - usu치rio
      description: 'Cadastro de usu치rio'
      operationId: 592819a0265360b2014512d6dbfaf0e7
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              properties:
                name:
                  type: string
                  example: Diego
                cpf:
                  type: string
                  example: '37128197060'
                password:
                  type: string
                  example: '19800507'
                email:
                  type: string
                  example: example@foo.com
              type: object
      responses:
        '200':
          description: 'Usu치rio criado'
externalDocs:
  description: 'C칩digo fonte do projeto'
  url: 'https://github.com/nenitf/elefanteca_api'
